import {
  ArrowRight,
  CheckCircle,
  ChevronDown,
  Facebook,
  Github,
  ChromeIcon as Google,
  Instagram,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Package,
  Plus,
  Search,
  ShoppingBag,
  ShoppingCart,
  Twitter,
  User,
  Youtube,
  AlertTriangle,
  Eye,
  EyeOff,
} from "lucide-react"

export const Icons = {
  logo: () => <>Dropics</>,
  spinner: Loader2,
  google: Google,
  arrowRight: ArrowRight,
  check: CheckCircle,
  mail: Mail,
  github: Github,
  user: User,
  menu: Menu,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  search: Search,
  chevronDown: ChevronDown,
  logOut: LogOut,
  packageIcon: Package,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  youtube: Youtube,
  plus: Plus,
  alertTriangle: AlertTriangle,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
}

